// <auto-generated />
namespace ARSFamily.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201905170822095_create user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
